### ISSUE TITLE
Internationalization Research

### ISSUE THREAD

**Issue by bmarani** [tawana0518/mywebclass-simulation#3]
As a global user of MyWebsite, I want the website to be inclusive and considerate of my specific language and accessibility needs, so that I can easily access and engage with the content offered, regardless of my location, language, or potential disabilities.

**Comment by rk864** [comment]
@bmarani @tawana0518  - Please review the issue and feel free to add/correct. we will discuss it further when we meet later evening today. thank you!

**Comment by rk864** [comment]
**Based on the current version of the MyWebClass.org website, it appears that the website does not have support for internationalization out of the box.** This means that in order to add support for internationalization, significant changes to the code and architecture of the website would likely be required.

To add internationalization to the website, some possible changes that would need to be made include:

1. Adding support for different languages throughout the website, such as translating text, images, and multimedia content.
2. Implementing a language switcher that allows users to select their preferred language.
3. Setting the language of the website based on the user's preferred language, as determined by their browser settings or the Accept-Language header.
4. These changes can be complex and time-consuming to implement, but they would be necessary in order to fully support internationalization on the website.

**Comment by rk864** [comment]
To add minimal internationalization to the website without breaking the existing functionality, I  haved followed these steps:

**Update the lang attribute in the html tag in index.html file to support dynamic language changes:**

html lang="{lang}"
...

**Created a JavaScript function in the main.js file to set the language attribute dynamically based on the user's language** preference:
function setLanguage() {
  // Get the user's preferred language
  const userLang = navigator.language || navigator.userLanguage;

  // Check if the user's language is supported (in this example, we're checking for English)
  const supportedLang = userLang.substring(0, 2).toLowerCase() === 'en' ? 'en' : 'en';

  // Set the 'lang' attribute of the 'html' tag to the supported language
  document.documentElement.setAttribute('lang', supportedLang);
}
**Call the setLanguage() function when the DOM content is loaded:**

document.addEventListener('DOMContentLoaded', () => {
  setLanguage();
  // ... Your other code
});
These changes will set the language attribute of the html tag to the supported language (in this example, English) when the page is loaded. Keep in mind that this example only checks for English language support. If you need to support more languages, you can modify the setLanguage function and add more conditions.

Note that this is just a simple example of setting the language attribute dynamically. For a more complete internationalization solution, you might want to use a library like [i18next](https://www.i18next.com/) or implement a more advanced language detection and content translation mechanism.
